### ISSUE TITLE
IRIS license expired, Docker build fails

### ISSUE THREAD

**Issue by rcemper** [rfns/iris-ci#9]
This copy of InterSystems IRIS has been licensed for use exclusively by:
Community License expired.

**Comment by rfns** [comment]
Hello @rcemper 

Can you provide me which version you used for your test?

**Comment by rcemper** [comment]
**here is it** >>> **Community License expired.**

>docker run --rm --name ci -t -v /path/to/your/app:/opt/ci/app rfns/iris-ci:0.6.1

Unable to find image 'rfns/iris-ci:0.6.1' locally
0.6.1: Pulling from rfns/iris-ci
898c46f3b1a1: Pull complete
63366dfa0a50: Pull complete
041d4cd74a92: Pull complete
6e1bee0f8701: Pull complete
973e47831f38: Pull complete
b0c3b996c3e3: Pull complete
b48eef952cda: Pull complete
8254746f78e2: Pull complete
ec1f0f74baf0: Pull complete
056450c8ed0f: Pull complete
115e9ee06fa9: Pull complete
7c12ef3622a4: Pull complete
e7013492547d: Pull complete
Digest: sha256:e4cb590fbfa99dd5383ea29103126ae0983d6efa6b3f7a4b68ff53643968982b
Status: Downloaded newer image for rfns/iris-ci:0.6.1
Starting IRIS
Starting Control Process
Automatically configuring buffers
Allocated 663MB shared memory: 476MB global buffers, 35MB routine buffers

This copy of InterSystems IRIS has been licensed for use exclusively by:
**Community License expired.**

Copyright (c) 1986-2019 by InterSystems Corporation
Any other use is a violation of your license agreement

2 alert(s) during startup. See messages.log for details.

**Comment by rfns** [comment]
@rcemper Ahh, ok!

There's actually an error in the README. I'll fix it later on, but you can try using the version 0.6.2.

**Comment by rfns** [comment]
Fixed in [bump iris version to latest tag](https://github.com/rfns/iris-ci/commit/f41b2143874ad0d5cd57975e063d4036f758481a)
[f41b214](https://github.com/rfns/iris-ci/commit/f41b2143874ad0d5cd57975e063d4036f758481a)
